#-------- detaset path -------
train_data_path: 
- ../dataset/data/npy/classical_jazz_1024/train
validation_data_path:
- ../dataset/data/npy/classical_jazz_1024/val
test_data_path:
- ../dataset/data/npy/classical_jazz_1024/test

#------ setting input data ------
data_length: 1024
input_names: ["midi"] #modalities of input data
input_shapes: #dims
  midi: [3, 1024, 128]

#------ train params ------
train_iteration: 50000
validation_interval: 1
checkpoint_interval: 200
batch_size: 8
learning_rate: 4.5e-6 #default: 4.5e-6
seed: 42
condition_type: text #condition type #text or class
use_clip_probvlm: False #flag of using text encoder


#------- setting using model -------
#support Diffusion
z_model:  #name of using model for obtain z
#support VAE
encoder: VAE #name of using model for encoder

#------- setting vae train mode -------
#Note: if you use discriminator and don't have pretrained model, you should train discriminator first.
train_discriminator: False #default: False